# LLM Configuration
llm:
  #model: "gpt-4o-mini-2024-07-18"
  model: "gpt-4.1-mini-2025-04-14"
  #api_endpoint: "https://api.openai.com/v1"
  #api_key: 'sk-proj-VKq9nXwA'
  api_endpoint: "https://api.zhizengzeng.com/v1"
  api_key: "skccf39bc"
  temperature: 0
  max_tokens: 32768

# Monitoring Configuration
monitor:
  interval_seconds: 60
  api_retries: 3
  retry_backoff_seconds: 5

# Troubleshooting Configuration
troubleshoot:
  timeout_seconds: 300
  interactive_mode: false
  auto_fix: false  # Enable/disable auto-fix mode
  mode: "standard" # Options: "standard" or "comprehensive"
  ssh:
    enabled: true
    user: "root"
    key_path: "~/.ssh/id_ed25519"
    nodes:
      - "kind-control-plane"
    retries: 3
    retry_backoff_seconds: 5

# Commands not allowed to be executed
commands:
  disallowed:
    - "fsck *"
    - "chmod *"
    - "chown *"
    - "dd *"
    - "mkfs *"
    - "rm *"
    - "kubectl delete *"
    - "kubectl apply *"
    - "xfs_repair *"  # Disallow non-diagnostic xfs_repair

# Logging Configuration
logging:
  file: "troubleshoot.log"
  stdout: true
