# LLM Configuration
llm:
  #model: "gpt-4-turbo-preview"
  #model: "gpt-4o-mini-2024-07-18"
  #model: "gpt-4.1-mini-2025-04-14"
  model: "gpt-4.1-nano-2025-04-14"
  #model: "grok-3-mini"
  #api_endpoint: "https://api.openai.com/v1"
  #api_key: 'sk-proj--'
  api_endpoint: "https://api.zhizengzeng.com/v1"
  api_key: "sk-"
  temperature: 0
  max_tokens: 8192

# Monitoring Configuration
monitor:
  interval_seconds: 60
  api_retries: 3
  retry_backoff_seconds: 5

plan_phase:
  use_llm: true  
  timeout_seconds: 1800
  static_plan_step_path: "data/static_plan_step.json"

# Troubleshooting Configuration
troubleshoot:
  timeout_seconds: 1800
  interactive_mode: false
  auto_fix: false  
  ssh:
    enabled: true
    user: "root"
    key_path: "~/.ssh/id_ed25519"
    nodes:
      - "my-cluster-control-plane"
      - "my-cluster-worker"
    retries: 3
    retry_backoff_seconds: 5

# Command Configuration
commands:
  allowed:
    - "kubectl *"
    - "smartctl *"
    - "fio *"
    - "df *"
    - "lsblk *"
    - "mount *"
    - "dmesg *"
    - "journalctl *"
    - "ssh *"
    - "sh *"
    - "xfs_repair -n *"
  disallowed:
    - "fsck *"
    - "chmod *"
    - "chown *"
    - "dd *"
    - "mkfs *"
    - "rm *"
    - "kubectl delete *"
    - "kubectl apply *"
    - "xfs_repair *"

# Logging Configuration
logging:
  file: "troubleshoot.log"
  stdout: true

# Historical Experience Configuration
historical_experience:
  file_path: "data/historical_experience.json"

# Chat Mode Configuration
chat_mode:
  enabled: true  # Enable or disable chat mode
  entry_points:
    #- "plan_phase"  # After Plan Phase
    - "phase1"      # After Phase1
