FROM kindest/node:v1.33.1

RUN apt-get update && \
    apt-get install -y xfsprogs && \
    apt-get install -y dmidecode && \
    apt-get install -y smartmontools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


